### ISSUE TITLE
Shockwave and Unity Web plugin games

### ISSUE THREAD

**Issue by HansServando** [Y8Games/Y8-Browser-releases#15]
I highly recommend that you add support for Shockwave and Unity Web plugins, as you do with flash. That would allow people to play a large number of games that your website hosts.

**Comment by EddieOne** [comment]
Hello, I looked into this and it didn't seem possible. In theory all plugins are the same except, I couldn't find downloads for most. Flash was recovered from archives. We are lucky to save Flash. Unity Web Player and Shockwave didn't make it though. Both work in IE 11 I think. 😬

**Comment by HansServando** [comment]
I've found the standalone installer of Shockwave Player at:
https://adobe-shockwave-player.softonic.com/
or more directly at:
https://www.softonic.com/descargar/adobe-shockwave-player/windows/post-descarga
and it is effectively the lastest version; and, as you say, it works in IE, for example, you can play Phosphor Beta smoothly.

And about Unity web player, i found it at:
https://unity-web-player.softonic.com/
or more directly at:
https://www.softonic.com/descargar/unity-web-player/windows/post-descarga
Unfortunately, this plugin doesn't seem to work in the oldest games.

**Comment by EddieOne** [comment]
We would need the plugins in Pepper format. https://www.chromium.org/developers/design-documents/pepper-plugin-implementation

Even then, it seems Flash received a lot of special attention these other plugins never got. In theory they should work but in reality they simple don't. The upstream software was not setup to easily support other plugins that I know of so far.

**Comment by HansServando** [comment]
I know. It means the support for NPAPI plugins had to be recovered, as in Waterfox, browsers with Goanna engine, among a few others.
Therefore, a interim solution would be to ensure that shockwave and Unity Web plugin games were playable in Internet Explorer.

**Comment by EddieOne** [comment]
Yeah, IE is less than ideal. Y8 used to have java applet games. They were removed eventually. Flash is in a similar situation. However, the Y8 browser is a fork of the chromium engine. So we have only the PPAPI.

**Comment by HansServando** [comment]
And the support of PPAPI will end in June 2022, too. 😕
https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html

**Comment by EddieOne** [comment]
I will make a note of this. It might not impact what is happening here. However, Flash is no longer being updated. So this is basically already a legacy project. The future is definitely html5 focused.

**Comment by HansServando** [comment]
Specially WebAssembly has a bright future.

**Comment by HansServando** [comment]
And for flash emulation the permanent solution in the near future seems to be ruffle.
