### ISSUE TITLE
Cant install y8 bowser

### ISSUE THREAD

**Issue by DarkAlex307** [Y8Games/Y8-Browser-releases#16]
The title says it all whenever i try setting up the browser it says "Your internet seems to be not permitted or or dropped out! Please reconnect and click retry to resume installation" when i press retry the same pop up shows up and when i press cancel it says "Unable to download application package from https://github.com/Y8Games/Y8-Flash-Browser/releases/download/v1.0.7/y8-browser-1.0.7--x64.nsis.7z (Status: SendRequest Error) Please check your connection and retry" is there a fix?

**Comment by EddieOne** [comment]
I suggest to download the .exe file and the 7z for your system. Either the x64 or x86. https://github.com/Y8Games/Y8-Flash-Browser/releases Then it should install without issues.
