### ISSUE TITLE
y8 browser not working

### ISSUE THREAD

**Issue by yeetusdeletus296432** [Y8Games/Y8-Browser-releases#18]
when I open y8 browser it says y8 browser.exe not found and the second error is when opening it closes can someone help.
This is the photo-->(https://user-images.githubusercontent.com/88212426/127710633-9315adbe-b46c-4aef-a6a2-5687a8ebffff.png)

**Comment by elenco23** [comment]
try deleting all the files of y8 browser and reinstall the browser.

**Comment by EddieOne** [comment]
In rare cases, you may encounter this bug while updating.  Downloading and reinstalling should work as well. https://www.y8.com/download-app
